version: "3.9"

services: 
  postgres:
    image: postgres:latest
    volumes:
      - swiezePostgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=swiezeWarzywa
    ports:
      - 5432:5432

volumes:
  swiezePostgres:
  
