// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SwiezeBackend.Helpers;

namespace SwiezeBackend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210717143535_Seed Contact Client UnitType")]
    partial class SeedContactClientUnitType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("SwiezeBackend.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ContactId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("ClientId");

                    b.HasIndex("ContactId")
                        .IsUnique();

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            ContactId = 1,
                            FirstName = "Joanna",
                            LastName = "Hand"
                        },
                        new
                        {
                            ClientId = 2,
                            ContactId = 2,
                            FirstName = "Leticia",
                            LastName = "Kihn"
                        },
                        new
                        {
                            ClientId = 3,
                            ContactId = 3,
                            FirstName = "Kelly",
                            LastName = "Berge"
                        },
                        new
                        {
                            ClientId = 4,
                            ContactId = 4,
                            FirstName = "Ken",
                            LastName = "Buckridge"
                        },
                        new
                        {
                            ClientId = 5,
                            ContactId = 5,
                            FirstName = "Tracy",
                            LastName = "Nader"
                        },
                        new
                        {
                            ClientId = 6,
                            ContactId = 6,
                            FirstName = "Albert",
                            LastName = "Cassin"
                        },
                        new
                        {
                            ClientId = 7,
                            ContactId = 7,
                            FirstName = "Glenda",
                            LastName = "Osinski"
                        },
                        new
                        {
                            ClientId = 8,
                            ContactId = 8,
                            FirstName = "Omar",
                            LastName = "Ziemann"
                        },
                        new
                        {
                            ClientId = 9,
                            ContactId = 9,
                            FirstName = "Al",
                            LastName = "Watsica"
                        },
                        new
                        {
                            ClientId = 10,
                            ContactId = 10,
                            FirstName = "Laurie",
                            LastName = "Wintheiser"
                        },
                        new
                        {
                            ClientId = 11,
                            ContactId = 11,
                            FirstName = "Glenn",
                            LastName = "Rice"
                        },
                        new
                        {
                            ClientId = 12,
                            ContactId = 12,
                            FirstName = "Roger",
                            LastName = "O'Kon"
                        },
                        new
                        {
                            ClientId = 13,
                            ContactId = 13,
                            FirstName = "Deanna",
                            LastName = "Hilll"
                        },
                        new
                        {
                            ClientId = 14,
                            ContactId = 14,
                            FirstName = "Nathaniel",
                            LastName = "Terry"
                        },
                        new
                        {
                            ClientId = 15,
                            ContactId = 15,
                            FirstName = "Janie",
                            LastName = "Langworth"
                        },
                        new
                        {
                            ClientId = 16,
                            ContactId = 16,
                            FirstName = "Mona",
                            LastName = "Weissnat"
                        },
                        new
                        {
                            ClientId = 17,
                            ContactId = 17,
                            FirstName = "Dwayne",
                            LastName = "Wilderman"
                        },
                        new
                        {
                            ClientId = 18,
                            ContactId = 18,
                            FirstName = "Irma",
                            LastName = "Kulas"
                        },
                        new
                        {
                            ClientId = 19,
                            ContactId = 19,
                            FirstName = "Rachael",
                            LastName = "Boyle"
                        },
                        new
                        {
                            ClientId = 20,
                            ContactId = 20,
                            FirstName = "Blanca",
                            LastName = "Prohaska"
                        },
                        new
                        {
                            ClientId = 21,
                            ContactId = 21,
                            FirstName = "Cornelius",
                            LastName = "D'Amore"
                        },
                        new
                        {
                            ClientId = 22,
                            ContactId = 22,
                            FirstName = "Dean",
                            LastName = "King"
                        },
                        new
                        {
                            ClientId = 23,
                            ContactId = 23,
                            FirstName = "Orville",
                            LastName = "Harber"
                        },
                        new
                        {
                            ClientId = 24,
                            ContactId = 24,
                            FirstName = "Michele",
                            LastName = "Lemke"
                        },
                        new
                        {
                            ClientId = 25,
                            ContactId = 25,
                            FirstName = "Jo",
                            LastName = "McGlynn"
                        },
                        new
                        {
                            ClientId = 26,
                            ContactId = 26,
                            FirstName = "Ignacio",
                            LastName = "Gulgowski"
                        },
                        new
                        {
                            ClientId = 27,
                            ContactId = 27,
                            FirstName = "Roy",
                            LastName = "Gusikowski"
                        },
                        new
                        {
                            ClientId = 28,
                            ContactId = 28,
                            FirstName = "Opal",
                            LastName = "Rodriguez"
                        },
                        new
                        {
                            ClientId = 29,
                            ContactId = 29,
                            FirstName = "Tina",
                            LastName = "Ruecker"
                        },
                        new
                        {
                            ClientId = 30,
                            ContactId = 30,
                            FirstName = "Tyrone",
                            LastName = "Heidenreich"
                        },
                        new
                        {
                            ClientId = 31,
                            ContactId = 31,
                            FirstName = "Mindy",
                            LastName = "Von"
                        },
                        new
                        {
                            ClientId = 32,
                            ContactId = 32,
                            FirstName = "Derek",
                            LastName = "Zboncak"
                        },
                        new
                        {
                            ClientId = 33,
                            ContactId = 33,
                            FirstName = "Joseph",
                            LastName = "Morar"
                        },
                        new
                        {
                            ClientId = 34,
                            ContactId = 34,
                            FirstName = "Warren",
                            LastName = "Mertz"
                        },
                        new
                        {
                            ClientId = 35,
                            ContactId = 35,
                            FirstName = "Anita",
                            LastName = "Prosacco"
                        },
                        new
                        {
                            ClientId = 36,
                            ContactId = 36,
                            FirstName = "Harriet",
                            LastName = "Wehner"
                        },
                        new
                        {
                            ClientId = 37,
                            ContactId = 37,
                            FirstName = "Toby",
                            LastName = "Ritchie"
                        },
                        new
                        {
                            ClientId = 38,
                            ContactId = 38,
                            FirstName = "Julio",
                            LastName = "Mann"
                        },
                        new
                        {
                            ClientId = 39,
                            ContactId = 39,
                            FirstName = "Opal",
                            LastName = "Ruecker"
                        },
                        new
                        {
                            ClientId = 40,
                            ContactId = 40,
                            FirstName = "Hattie",
                            LastName = "Herzog"
                        },
                        new
                        {
                            ClientId = 41,
                            ContactId = 41,
                            FirstName = "Rafael",
                            LastName = "Koelpin"
                        },
                        new
                        {
                            ClientId = 42,
                            ContactId = 42,
                            FirstName = "Janis",
                            LastName = "Roberts"
                        },
                        new
                        {
                            ClientId = 43,
                            ContactId = 43,
                            FirstName = "Leland",
                            LastName = "Collier"
                        },
                        new
                        {
                            ClientId = 44,
                            ContactId = 44,
                            FirstName = "Rolando",
                            LastName = "Gusikowski"
                        },
                        new
                        {
                            ClientId = 45,
                            ContactId = 45,
                            FirstName = "Raquel",
                            LastName = "Collier"
                        },
                        new
                        {
                            ClientId = 46,
                            ContactId = 46,
                            FirstName = "Marlon",
                            LastName = "Cronin"
                        },
                        new
                        {
                            ClientId = 47,
                            ContactId = 47,
                            FirstName = "Sophia",
                            LastName = "Monahan"
                        },
                        new
                        {
                            ClientId = 48,
                            ContactId = 48,
                            FirstName = "Roman",
                            LastName = "Frami"
                        },
                        new
                        {
                            ClientId = 49,
                            ContactId = 49,
                            FirstName = "Brendan",
                            LastName = "Lindgren"
                        },
                        new
                        {
                            ClientId = 50,
                            ContactId = 50,
                            FirstName = "Geraldine",
                            LastName = "Corkery"
                        },
                        new
                        {
                            ClientId = 51,
                            ContactId = 51,
                            FirstName = "Tracy",
                            LastName = "Boyle"
                        },
                        new
                        {
                            ClientId = 52,
                            ContactId = 52,
                            FirstName = "Dana",
                            LastName = "Huels"
                        },
                        new
                        {
                            ClientId = 53,
                            ContactId = 53,
                            FirstName = "Amanda",
                            LastName = "Reichert"
                        },
                        new
                        {
                            ClientId = 54,
                            ContactId = 54,
                            FirstName = "Abel",
                            LastName = "Johns"
                        },
                        new
                        {
                            ClientId = 55,
                            ContactId = 55,
                            FirstName = "Ora",
                            LastName = "Hagenes"
                        },
                        new
                        {
                            ClientId = 56,
                            ContactId = 56,
                            FirstName = "Lynda",
                            LastName = "Langosh"
                        },
                        new
                        {
                            ClientId = 57,
                            ContactId = 57,
                            FirstName = "Kim",
                            LastName = "Walsh"
                        },
                        new
                        {
                            ClientId = 58,
                            ContactId = 58,
                            FirstName = "Pete",
                            LastName = "Jast"
                        },
                        new
                        {
                            ClientId = 59,
                            ContactId = 59,
                            FirstName = "Aaron",
                            LastName = "White"
                        },
                        new
                        {
                            ClientId = 60,
                            ContactId = 60,
                            FirstName = "Sally",
                            LastName = "Ortiz"
                        },
                        new
                        {
                            ClientId = 61,
                            ContactId = 61,
                            FirstName = "Lester",
                            LastName = "Fisher"
                        },
                        new
                        {
                            ClientId = 62,
                            ContactId = 62,
                            FirstName = "Felicia",
                            LastName = "Brakus"
                        },
                        new
                        {
                            ClientId = 63,
                            ContactId = 63,
                            FirstName = "Juana",
                            LastName = "Miller"
                        },
                        new
                        {
                            ClientId = 64,
                            ContactId = 64,
                            FirstName = "Pam",
                            LastName = "Labadie"
                        },
                        new
                        {
                            ClientId = 65,
                            ContactId = 65,
                            FirstName = "Al",
                            LastName = "Rolfson"
                        },
                        new
                        {
                            ClientId = 66,
                            ContactId = 66,
                            FirstName = "Donna",
                            LastName = "Klein"
                        },
                        new
                        {
                            ClientId = 67,
                            ContactId = 67,
                            FirstName = "Anna",
                            LastName = "Schowalter"
                        },
                        new
                        {
                            ClientId = 68,
                            ContactId = 68,
                            FirstName = "Wilbert",
                            LastName = "Vandervort"
                        },
                        new
                        {
                            ClientId = 69,
                            ContactId = 69,
                            FirstName = "Wilson",
                            LastName = "Harvey"
                        },
                        new
                        {
                            ClientId = 70,
                            ContactId = 70,
                            FirstName = "Jan",
                            LastName = "Powlowski"
                        },
                        new
                        {
                            ClientId = 71,
                            ContactId = 71,
                            FirstName = "Candice",
                            LastName = "Grimes"
                        },
                        new
                        {
                            ClientId = 72,
                            ContactId = 72,
                            FirstName = "Natalie",
                            LastName = "Sporer"
                        },
                        new
                        {
                            ClientId = 73,
                            ContactId = 73,
                            FirstName = "Andres",
                            LastName = "Waters"
                        },
                        new
                        {
                            ClientId = 74,
                            ContactId = 74,
                            FirstName = "Willie",
                            LastName = "Mante"
                        },
                        new
                        {
                            ClientId = 75,
                            ContactId = 75,
                            FirstName = "Paulette",
                            LastName = "Ziemann"
                        },
                        new
                        {
                            ClientId = 76,
                            ContactId = 76,
                            FirstName = "Caroline",
                            LastName = "Farrell"
                        },
                        new
                        {
                            ClientId = 77,
                            ContactId = 77,
                            FirstName = "Loretta",
                            LastName = "Langosh"
                        },
                        new
                        {
                            ClientId = 78,
                            ContactId = 78,
                            FirstName = "Alfred",
                            LastName = "Hermann"
                        },
                        new
                        {
                            ClientId = 79,
                            ContactId = 79,
                            FirstName = "Amber",
                            LastName = "Sauer"
                        },
                        new
                        {
                            ClientId = 80,
                            ContactId = 80,
                            FirstName = "Marcia",
                            LastName = "Pfannerstill"
                        },
                        new
                        {
                            ClientId = 81,
                            ContactId = 81,
                            FirstName = "Jeff",
                            LastName = "Thompson"
                        },
                        new
                        {
                            ClientId = 82,
                            ContactId = 82,
                            FirstName = "Raymond",
                            LastName = "Zboncak"
                        },
                        new
                        {
                            ClientId = 83,
                            ContactId = 83,
                            FirstName = "Bradley",
                            LastName = "Moore"
                        },
                        new
                        {
                            ClientId = 84,
                            ContactId = 84,
                            FirstName = "Vicky",
                            LastName = "Stark"
                        },
                        new
                        {
                            ClientId = 85,
                            ContactId = 85,
                            FirstName = "Judith",
                            LastName = "Glover"
                        },
                        new
                        {
                            ClientId = 86,
                            ContactId = 86,
                            FirstName = "Kent",
                            LastName = "Hilpert"
                        },
                        new
                        {
                            ClientId = 87,
                            ContactId = 87,
                            FirstName = "Daisy",
                            LastName = "Langworth"
                        },
                        new
                        {
                            ClientId = 88,
                            ContactId = 88,
                            FirstName = "Ismael",
                            LastName = "Weber"
                        },
                        new
                        {
                            ClientId = 89,
                            ContactId = 89,
                            FirstName = "Candice",
                            LastName = "Lowe"
                        },
                        new
                        {
                            ClientId = 90,
                            ContactId = 90,
                            FirstName = "Francisco",
                            LastName = "Pollich"
                        },
                        new
                        {
                            ClientId = 91,
                            ContactId = 91,
                            FirstName = "Carolyn",
                            LastName = "Kub"
                        },
                        new
                        {
                            ClientId = 92,
                            ContactId = 92,
                            FirstName = "Kayla",
                            LastName = "Raynor"
                        },
                        new
                        {
                            ClientId = 93,
                            ContactId = 93,
                            FirstName = "Robin",
                            LastName = "Aufderhar"
                        },
                        new
                        {
                            ClientId = 94,
                            ContactId = 94,
                            FirstName = "Jordan",
                            LastName = "Maggio"
                        },
                        new
                        {
                            ClientId = 95,
                            ContactId = 95,
                            FirstName = "Tom",
                            LastName = "Bartell"
                        },
                        new
                        {
                            ClientId = 96,
                            ContactId = 96,
                            FirstName = "Santos",
                            LastName = "Franecki"
                        },
                        new
                        {
                            ClientId = 97,
                            ContactId = 97,
                            FirstName = "Gordon",
                            LastName = "Cole"
                        },
                        new
                        {
                            ClientId = 98,
                            ContactId = 98,
                            FirstName = "Dexter",
                            LastName = "Prosacco"
                        },
                        new
                        {
                            ClientId = 99,
                            ContactId = 99,
                            FirstName = "Maggie",
                            LastName = "Pfeffer"
                        },
                        new
                        {
                            ClientId = 100,
                            ContactId = 100,
                            FirstName = "Kendra",
                            LastName = "Mann"
                        });
                });

            modelBuilder.Entity("SwiezeBackend.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("FlatNumber")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Voivodeship")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            City = "Lake Mohamedbury",
                            FlatNumber = "97Z",
                            HouseNumber = "8537",
                            Mail = "Halie48@hotmail.com",
                            Phone = "804892815",
                            PostalCode = "64-780",
                            Street = "Bailee Expressway",
                            Voivodeship = "Pennsylvania"
                        },
                        new
                        {
                            ContactId = 2,
                            City = "New Garrisonbury",
                            FlatNumber = "67",
                            HouseNumber = "2625",
                            Mail = "Kaia25@hotmail.com",
                            Phone = "238569164",
                            PostalCode = "48-927",
                            Street = "Margarett Streets",
                            Voivodeship = "Tennessee"
                        },
                        new
                        {
                            ContactId = 3,
                            City = "New Keaton",
                            FlatNumber = "2R",
                            HouseNumber = "52912",
                            Mail = "Frida_Armstrong@hotmail.com",
                            Phone = "288544533",
                            PostalCode = "95-582",
                            Street = "Ernser Courts",
                            Voivodeship = "Washington"
                        },
                        new
                        {
                            ContactId = 4,
                            City = "Glovermouth",
                            FlatNumber = "0",
                            HouseNumber = "74682",
                            Mail = "Brando0@yahoo.com",
                            Phone = "496711471",
                            PostalCode = "89-438",
                            Street = "Goyette Plains",
                            Voivodeship = "Wisconsin"
                        },
                        new
                        {
                            ContactId = 5,
                            City = "West Queenville",
                            FlatNumber = "644H",
                            HouseNumber = "4926",
                            Mail = "Scot29@yahoo.com",
                            Phone = "115369061",
                            PostalCode = "52-678",
                            Street = "Corene Tunnel",
                            Voivodeship = "Rhode Island"
                        },
                        new
                        {
                            ContactId = 6,
                            City = "Port Daren",
                            FlatNumber = "67F",
                            HouseNumber = "830",
                            Mail = "Krystel4@hotmail.com",
                            Phone = "505670197",
                            PostalCode = "97-639",
                            Street = "Alyce Cape",
                            Voivodeship = "California"
                        },
                        new
                        {
                            ContactId = 7,
                            City = "West Patiencefurt",
                            FlatNumber = "1",
                            HouseNumber = "2375",
                            Mail = "Alia_Connelly@gmail.com",
                            Phone = "739039160",
                            PostalCode = "13-042",
                            Street = "Gaetano Trace",
                            Voivodeship = "Colorado"
                        },
                        new
                        {
                            ContactId = 8,
                            City = "Pfannerstillshire",
                            FlatNumber = "3U",
                            HouseNumber = "605",
                            Mail = "Gail_OReilly@yahoo.com",
                            Phone = "884450304",
                            PostalCode = "06-130",
                            Street = "Lessie Freeway",
                            Voivodeship = "Oregon"
                        },
                        new
                        {
                            ContactId = 9,
                            City = "Yasmineshire",
                            FlatNumber = "593",
                            HouseNumber = "7714",
                            Mail = "Quinten_Considine@hotmail.com",
                            Phone = "476800644",
                            PostalCode = "66-333",
                            Street = "Karlee Hill",
                            Voivodeship = "Montana"
                        },
                        new
                        {
                            ContactId = 10,
                            City = "Port Emie",
                            FlatNumber = "199Q",
                            HouseNumber = "83300",
                            Mail = "Esteban.Cruickshank29@gmail.com",
                            Phone = "581868454",
                            PostalCode = "95-935",
                            Street = "Bailey Mount",
                            Voivodeship = "North Dakota"
                        },
                        new
                        {
                            ContactId = 11,
                            City = "South Cyril",
                            FlatNumber = "22O",
                            HouseNumber = "6157",
                            Mail = "Gregg44@yahoo.com",
                            Phone = "201184793",
                            PostalCode = "39-757",
                            Street = "Clare Way",
                            Voivodeship = "Massachusetts"
                        },
                        new
                        {
                            ContactId = 12,
                            City = "New Shyannborough",
                            FlatNumber = "293W",
                            HouseNumber = "752",
                            Mail = "Abelardo45@gmail.com",
                            Phone = "937258777",
                            PostalCode = "42-521",
                            Street = "Johnston Turnpike",
                            Voivodeship = "Florida"
                        },
                        new
                        {
                            ContactId = 13,
                            City = "Kassulketown",
                            FlatNumber = "2",
                            HouseNumber = "616",
                            Mail = "Terence_Romaguera@gmail.com",
                            Phone = "756744512",
                            PostalCode = "54-694",
                            Street = "Charlotte Prairie",
                            Voivodeship = "Illinois"
                        },
                        new
                        {
                            ContactId = 14,
                            City = "North Adolphusmouth",
                            FlatNumber = "9U",
                            HouseNumber = "4252",
                            Mail = "Karlee70@hotmail.com",
                            Phone = "597689949",
                            PostalCode = "64-586",
                            Street = "Myrtle Dale",
                            Voivodeship = "Louisiana"
                        },
                        new
                        {
                            ContactId = 15,
                            City = "Lake Efren",
                            FlatNumber = "4M",
                            HouseNumber = "89534",
                            Mail = "Emmet26@gmail.com",
                            Phone = "749543843",
                            PostalCode = "40-919",
                            Street = "Rosina Orchard",
                            Voivodeship = "South Dakota"
                        },
                        new
                        {
                            ContactId = 16,
                            City = "West Josephinechester",
                            FlatNumber = "863",
                            HouseNumber = "96137",
                            Mail = "Geovany.Walsh19@gmail.com",
                            Phone = "284202846",
                            PostalCode = "32-321",
                            Street = "Waelchi Field",
                            Voivodeship = "New York"
                        },
                        new
                        {
                            ContactId = 17,
                            City = "Idellaland",
                            FlatNumber = "8",
                            HouseNumber = "51291",
                            Mail = "Myron26@hotmail.com",
                            Phone = "643601002",
                            PostalCode = "66-225",
                            Street = "Kareem Roads",
                            Voivodeship = "Kansas"
                        },
                        new
                        {
                            ContactId = 18,
                            City = "Masonview",
                            FlatNumber = "36C",
                            HouseNumber = "716",
                            Mail = "Kirk.Parker40@hotmail.com",
                            Phone = "608897949",
                            PostalCode = "19-025",
                            Street = "Paucek Inlet",
                            Voivodeship = "Utah"
                        },
                        new
                        {
                            ContactId = 19,
                            City = "Eldaside",
                            FlatNumber = "520",
                            HouseNumber = "75109",
                            Mail = "Henri95@gmail.com",
                            Phone = "164513456",
                            PostalCode = "81-509",
                            Street = "Jovany Radial",
                            Voivodeship = "Tennessee"
                        },
                        new
                        {
                            ContactId = 20,
                            City = "Schadenfort",
                            FlatNumber = "1",
                            HouseNumber = "13838",
                            Mail = "Sheila49@hotmail.com",
                            Phone = "967728830",
                            PostalCode = "57-645",
                            Street = "Everett Motorway",
                            Voivodeship = "Utah"
                        },
                        new
                        {
                            ContactId = 21,
                            City = "Bradtketown",
                            FlatNumber = "26Q",
                            HouseNumber = "09498",
                            Mail = "Destiney.Bednar18@gmail.com",
                            Phone = "726508555",
                            PostalCode = "13-908",
                            Street = "Goodwin Cove",
                            Voivodeship = "Wisconsin"
                        },
                        new
                        {
                            ContactId = 22,
                            City = "North Heberhaven",
                            FlatNumber = "3",
                            HouseNumber = "911",
                            Mail = "Dereck.Grimes@hotmail.com",
                            Phone = "850821978",
                            PostalCode = "08-304",
                            Street = "Rosalee Row",
                            Voivodeship = "Maryland"
                        },
                        new
                        {
                            ContactId = 23,
                            City = "West Berenicechester",
                            FlatNumber = "973",
                            HouseNumber = "134",
                            Mail = "Bette51@yahoo.com",
                            Phone = "712804335",
                            PostalCode = "73-261",
                            Street = "Bailey Underpass",
                            Voivodeship = "Maine"
                        },
                        new
                        {
                            ContactId = 24,
                            City = "Port Christymouth",
                            FlatNumber = "387P",
                            HouseNumber = "1226",
                            Mail = "Chelsie0@yahoo.com",
                            Phone = "970928858",
                            PostalCode = "83-340",
                            Street = "Nikolaus Common",
                            Voivodeship = "Colorado"
                        },
                        new
                        {
                            ContactId = 25,
                            City = "North Bret",
                            FlatNumber = "3",
                            HouseNumber = "60892",
                            Mail = "Lera_Bashirian@yahoo.com",
                            Phone = "471404432",
                            PostalCode = "14-595",
                            Street = "Kolby Isle",
                            Voivodeship = "Georgia"
                        },
                        new
                        {
                            ContactId = 26,
                            City = "Lilianstad",
                            FlatNumber = "57E",
                            HouseNumber = "231",
                            Mail = "Stella_Botsford@hotmail.com",
                            Phone = "917135186",
                            PostalCode = "72-344",
                            Street = "Mable Key",
                            Voivodeship = "South Carolina"
                        },
                        new
                        {
                            ContactId = 27,
                            City = "Aufderharstad",
                            FlatNumber = "59",
                            HouseNumber = "8391",
                            Mail = "Jessy.Homenick41@yahoo.com",
                            Phone = "560046478",
                            PostalCode = "36-031",
                            Street = "Emmie Ford",
                            Voivodeship = "Rhode Island"
                        },
                        new
                        {
                            ContactId = 28,
                            City = "Rosenbaumhaven",
                            FlatNumber = "6",
                            HouseNumber = "529",
                            Mail = "Caterina.Deckow75@gmail.com",
                            Phone = "466185633",
                            PostalCode = "01-599",
                            Street = "Gaston Island",
                            Voivodeship = "Montana"
                        },
                        new
                        {
                            ContactId = 29,
                            City = "North Genovevafort",
                            FlatNumber = "6X",
                            HouseNumber = "6258",
                            Mail = "Amya_Stracke80@hotmail.com",
                            Phone = "454542676",
                            PostalCode = "20-353",
                            Street = "Huels Bypass",
                            Voivodeship = "Montana"
                        },
                        new
                        {
                            ContactId = 30,
                            City = "Wolfffort",
                            FlatNumber = "16",
                            HouseNumber = "2768",
                            Mail = "Brian.Huel@gmail.com",
                            Phone = "262647809",
                            PostalCode = "75-548",
                            Street = "Hammes Crossroad",
                            Voivodeship = "Georgia"
                        },
                        new
                        {
                            ContactId = 31,
                            City = "Port Jamir",
                            FlatNumber = "0",
                            HouseNumber = "0437",
                            Mail = "Elna.Stanton@hotmail.com",
                            Phone = "785657489",
                            PostalCode = "90-930",
                            Street = "Stracke Mews",
                            Voivodeship = "Indiana"
                        },
                        new
                        {
                            ContactId = 32,
                            City = "Lehnerburgh",
                            FlatNumber = "7W",
                            HouseNumber = "6473",
                            Mail = "Marta50@hotmail.com",
                            Phone = "734817748",
                            PostalCode = "61-059",
                            Street = "Clement Expressway",
                            Voivodeship = "South Dakota"
                        },
                        new
                        {
                            ContactId = 33,
                            City = "Schambergershire",
                            FlatNumber = "8H",
                            HouseNumber = "51800",
                            Mail = "Marcos_Bednar23@yahoo.com",
                            Phone = "337307653",
                            PostalCode = "46-023",
                            Street = "Brekke Via",
                            Voivodeship = "Nebraska"
                        },
                        new
                        {
                            ContactId = 34,
                            City = "Gutmannbury",
                            FlatNumber = "871S",
                            HouseNumber = "18941",
                            Mail = "Sage47@hotmail.com",
                            Phone = "169230667",
                            PostalCode = "76-275",
                            Street = "Virginia Mission",
                            Voivodeship = "Louisiana"
                        },
                        new
                        {
                            ContactId = 35,
                            City = "Mitchellhaven",
                            FlatNumber = "5J",
                            HouseNumber = "108",
                            Mail = "Caden_Rath@gmail.com",
                            Phone = "268925757",
                            PostalCode = "42-497",
                            Street = "Pacocha Divide",
                            Voivodeship = "Tennessee"
                        },
                        new
                        {
                            ContactId = 36,
                            City = "Port Elfriedabury",
                            FlatNumber = "0J",
                            HouseNumber = "90488",
                            Mail = "Jammie_Tremblay@gmail.com",
                            Phone = "370393625",
                            PostalCode = "85-222",
                            Street = "Rau Groves",
                            Voivodeship = "West Virginia"
                        },
                        new
                        {
                            ContactId = 37,
                            City = "Port Lea",
                            FlatNumber = "81L",
                            HouseNumber = "5908",
                            Mail = "Kamron_Krajcik@gmail.com",
                            Phone = "460969879",
                            PostalCode = "68-720",
                            Street = "Breanna Mission",
                            Voivodeship = "Indiana"
                        },
                        new
                        {
                            ContactId = 38,
                            City = "South Maureenside",
                            FlatNumber = "74D",
                            HouseNumber = "93766",
                            Mail = "Juliana53@hotmail.com",
                            Phone = "723505106",
                            PostalCode = "05-539",
                            Street = "Tiffany Forks",
                            Voivodeship = "South Carolina"
                        },
                        new
                        {
                            ContactId = 39,
                            City = "Port Dominiquemouth",
                            FlatNumber = "3P",
                            HouseNumber = "85559",
                            Mail = "Columbus_Wolff5@hotmail.com",
                            Phone = "610578718",
                            PostalCode = "90-401",
                            Street = "Blick Underpass",
                            Voivodeship = "Pennsylvania"
                        },
                        new
                        {
                            ContactId = 40,
                            City = "Murphyport",
                            FlatNumber = "1",
                            HouseNumber = "500",
                            Mail = "Shemar93@gmail.com",
                            Phone = "490741240",
                            PostalCode = "32-303",
                            Street = "Krajcik Mission",
                            Voivodeship = "North Carolina"
                        },
                        new
                        {
                            ContactId = 41,
                            City = "Peytonton",
                            FlatNumber = "84N",
                            HouseNumber = "9448",
                            Mail = "Jules_OKeefe5@yahoo.com",
                            Phone = "481523246",
                            PostalCode = "49-561",
                            Street = "Schneider Fields",
                            Voivodeship = "Nevada"
                        },
                        new
                        {
                            ContactId = 42,
                            City = "Verdahaven",
                            FlatNumber = "622R",
                            HouseNumber = "138",
                            Mail = "Norma11@gmail.com",
                            Phone = "744927491",
                            PostalCode = "25-314",
                            Street = "Adams Garden",
                            Voivodeship = "New Jersey"
                        },
                        new
                        {
                            ContactId = 43,
                            City = "Lake Tracy",
                            FlatNumber = "54",
                            HouseNumber = "45593",
                            Mail = "Bert_Sanford31@yahoo.com",
                            Phone = "278828085",
                            PostalCode = "81-524",
                            Street = "Weissnat Meadow",
                            Voivodeship = "Kentucky"
                        },
                        new
                        {
                            ContactId = 44,
                            City = "Morissetteland",
                            FlatNumber = "4X",
                            HouseNumber = "28126",
                            Mail = "Devante69@yahoo.com",
                            Phone = "589325692",
                            PostalCode = "27-510",
                            Street = "Iliana Terrace",
                            Voivodeship = "Florida"
                        },
                        new
                        {
                            ContactId = 45,
                            City = "Rogahnburgh",
                            FlatNumber = "48",
                            HouseNumber = "91610",
                            Mail = "Oren_Lind@hotmail.com",
                            Phone = "759598069",
                            PostalCode = "77-371",
                            Street = "Julian Harbors",
                            Voivodeship = "Wisconsin"
                        },
                        new
                        {
                            ContactId = 46,
                            City = "Port Kurtchester",
                            FlatNumber = "691J",
                            HouseNumber = "966",
                            Mail = "Melody3@gmail.com",
                            Phone = "812371666",
                            PostalCode = "22-976",
                            Street = "Jerod Junction",
                            Voivodeship = "Alabama"
                        },
                        new
                        {
                            ContactId = 47,
                            City = "East Hilbert",
                            FlatNumber = "162",
                            HouseNumber = "1365",
                            Mail = "Freddie_Prohaska@yahoo.com",
                            Phone = "636977602",
                            PostalCode = "17-226",
                            Street = "Colt Mill",
                            Voivodeship = "Maryland"
                        },
                        new
                        {
                            ContactId = 48,
                            City = "Marcellaside",
                            FlatNumber = "0C",
                            HouseNumber = "9274",
                            Mail = "Landen.Langworth61@gmail.com",
                            Phone = "146012079",
                            PostalCode = "31-178",
                            Street = "Jayne Forest",
                            Voivodeship = "Hawaii"
                        },
                        new
                        {
                            ContactId = 49,
                            City = "North Adolphus",
                            FlatNumber = "22O",
                            HouseNumber = "12885",
                            Mail = "Nicole62@yahoo.com",
                            Phone = "935116146",
                            PostalCode = "56-208",
                            Street = "Russel Walk",
                            Voivodeship = "Oklahoma"
                        },
                        new
                        {
                            ContactId = 50,
                            City = "East Timmy",
                            FlatNumber = "0",
                            HouseNumber = "90350",
                            Mail = "Eda.Feest72@hotmail.com",
                            Phone = "219130968",
                            PostalCode = "83-720",
                            Street = "Jacobi Mills",
                            Voivodeship = "Connecticut"
                        },
                        new
                        {
                            ContactId = 51,
                            City = "Skilesport",
                            FlatNumber = "326R",
                            HouseNumber = "3520",
                            Mail = "Brittany24@yahoo.com",
                            Phone = "935746757",
                            PostalCode = "83-481",
                            Street = "Stanton Creek",
                            Voivodeship = "South Dakota"
                        },
                        new
                        {
                            ContactId = 52,
                            City = "South Rosendoville",
                            FlatNumber = "5O",
                            HouseNumber = "88056",
                            Mail = "Beryl.Mueller@hotmail.com",
                            Phone = "493358213",
                            PostalCode = "16-025",
                            Street = "Xzavier Mews",
                            Voivodeship = "New York"
                        },
                        new
                        {
                            ContactId = 53,
                            City = "Lake Verla",
                            FlatNumber = "67M",
                            HouseNumber = "91727",
                            Mail = "Vicente.Pfannerstill21@gmail.com",
                            Phone = "721774833",
                            PostalCode = "85-412",
                            Street = "Jaren Brooks",
                            Voivodeship = "New Mexico"
                        },
                        new
                        {
                            ContactId = 54,
                            City = "Lake Pasquale",
                            FlatNumber = "20",
                            HouseNumber = "1510",
                            Mail = "Assunta56@yahoo.com",
                            Phone = "647696545",
                            PostalCode = "16-195",
                            Street = "Sanford Corner",
                            Voivodeship = "South Carolina"
                        },
                        new
                        {
                            ContactId = 55,
                            City = "North River",
                            FlatNumber = "58",
                            HouseNumber = "54941",
                            Mail = "Vivienne4@yahoo.com",
                            Phone = "334117160",
                            PostalCode = "27-193",
                            Street = "Cary Spur",
                            Voivodeship = "Maine"
                        },
                        new
                        {
                            ContactId = 56,
                            City = "Herzogfort",
                            FlatNumber = "898H",
                            HouseNumber = "03475",
                            Mail = "Gregory_Rau63@gmail.com",
                            Phone = "519936256",
                            PostalCode = "20-547",
                            Street = "Audra Expressway",
                            Voivodeship = "South Dakota"
                        },
                        new
                        {
                            ContactId = 57,
                            City = "East Katlynnmouth",
                            FlatNumber = "0",
                            HouseNumber = "734",
                            Mail = "Micah.Runolfsdottir@gmail.com",
                            Phone = "555821719",
                            PostalCode = "02-749",
                            Street = "Jast Skyway",
                            Voivodeship = "South Carolina"
                        },
                        new
                        {
                            ContactId = 58,
                            City = "North Carterstad",
                            FlatNumber = "29",
                            HouseNumber = "2134",
                            Mail = "Xzavier.Bartoletti@hotmail.com",
                            Phone = "391507402",
                            PostalCode = "94-334",
                            Street = "Reina Mountain",
                            Voivodeship = "Massachusetts"
                        },
                        new
                        {
                            ContactId = 59,
                            City = "North Donnellchester",
                            FlatNumber = "8D",
                            HouseNumber = "15379",
                            Mail = "Shana_Kuhlman4@gmail.com",
                            Phone = "315053399",
                            PostalCode = "05-206",
                            Street = "Dooley Stream",
                            Voivodeship = "Mississippi"
                        },
                        new
                        {
                            ContactId = 60,
                            City = "East Johnathonland",
                            FlatNumber = "33",
                            HouseNumber = "22621",
                            Mail = "Kallie83@hotmail.com",
                            Phone = "694453909",
                            PostalCode = "86-922",
                            Street = "Delmer Parkways",
                            Voivodeship = "North Dakota"
                        },
                        new
                        {
                            ContactId = 61,
                            City = "Port Ernie",
                            FlatNumber = "32N",
                            HouseNumber = "455",
                            Mail = "Electa_Keeling@hotmail.com",
                            Phone = "635722159",
                            PostalCode = "46-957",
                            Street = "Jovan Keys",
                            Voivodeship = "Kentucky"
                        },
                        new
                        {
                            ContactId = 62,
                            City = "Whitneyburgh",
                            FlatNumber = "27Z",
                            HouseNumber = "7379",
                            Mail = "Candelario.Schinner@yahoo.com",
                            Phone = "473103008",
                            PostalCode = "74-179",
                            Street = "Koss Highway",
                            Voivodeship = "North Dakota"
                        },
                        new
                        {
                            ContactId = 63,
                            City = "East Jeanetteside",
                            FlatNumber = "958",
                            HouseNumber = "317",
                            Mail = "Enrique_Orn45@yahoo.com",
                            Phone = "823704775",
                            PostalCode = "36-669",
                            Street = "Gaylord Port",
                            Voivodeship = "Minnesota"
                        },
                        new
                        {
                            ContactId = 64,
                            City = "East Marvin",
                            FlatNumber = "536",
                            HouseNumber = "827",
                            Mail = "Verdie29@hotmail.com",
                            Phone = "565858004",
                            PostalCode = "11-417",
                            Street = "Quigley Fields",
                            Voivodeship = "Texas"
                        },
                        new
                        {
                            ContactId = 65,
                            City = "West Clare",
                            FlatNumber = "06H",
                            HouseNumber = "0185",
                            Mail = "Priscilla.Torp@hotmail.com",
                            Phone = "730726332",
                            PostalCode = "66-347",
                            Street = "Muller Union",
                            Voivodeship = "Delaware"
                        },
                        new
                        {
                            ContactId = 66,
                            City = "Herzogland",
                            FlatNumber = "60U",
                            HouseNumber = "775",
                            Mail = "Chauncey_Cruickshank37@hotmail.com",
                            Phone = "969205492",
                            PostalCode = "01-020",
                            Street = "Hand Parks",
                            Voivodeship = "Alaska"
                        },
                        new
                        {
                            ContactId = 67,
                            City = "Gutmanntown",
                            FlatNumber = "34R",
                            HouseNumber = "97678",
                            Mail = "Jean_Tremblay@yahoo.com",
                            Phone = "580266713",
                            PostalCode = "20-166",
                            Street = "Stark Skyway",
                            Voivodeship = "Idaho"
                        },
                        new
                        {
                            ContactId = 68,
                            City = "East Aurore",
                            FlatNumber = "726B",
                            HouseNumber = "107",
                            Mail = "Curtis_DuBuque@hotmail.com",
                            Phone = "448473617",
                            PostalCode = "46-988",
                            Street = "Frami Orchard",
                            Voivodeship = "North Carolina"
                        },
                        new
                        {
                            ContactId = 69,
                            City = "North Stevefort",
                            FlatNumber = "4X",
                            HouseNumber = "1387",
                            Mail = "Aliya_Gusikowski@hotmail.com",
                            Phone = "941263712",
                            PostalCode = "19-431",
                            Street = "Meagan Isle",
                            Voivodeship = "Mississippi"
                        },
                        new
                        {
                            ContactId = 70,
                            City = "South Quinnside",
                            FlatNumber = "957Z",
                            HouseNumber = "3264",
                            Mail = "Walton_Kovacek@gmail.com",
                            Phone = "884861923",
                            PostalCode = "34-883",
                            Street = "Nitzsche Stravenue",
                            Voivodeship = "New York"
                        },
                        new
                        {
                            ContactId = 71,
                            City = "Ronaldoville",
                            FlatNumber = "27",
                            HouseNumber = "007",
                            Mail = "Dawn_Rowe@yahoo.com",
                            Phone = "965755514",
                            PostalCode = "43-894",
                            Street = "Tyrese Forest",
                            Voivodeship = "Maine"
                        },
                        new
                        {
                            ContactId = 72,
                            City = "West Zeldastad",
                            FlatNumber = "10S",
                            HouseNumber = "71851",
                            Mail = "Marjorie_Wiza@hotmail.com",
                            Phone = "749891651",
                            PostalCode = "57-853",
                            Street = "Cheyenne Union",
                            Voivodeship = "Maryland"
                        },
                        new
                        {
                            ContactId = 73,
                            City = "Rooseveltfurt",
                            FlatNumber = "159",
                            HouseNumber = "4997",
                            Mail = "Aniyah.Gislason80@gmail.com",
                            Phone = "201420304",
                            PostalCode = "92-817",
                            Street = "Abshire Ville",
                            Voivodeship = "Indiana"
                        },
                        new
                        {
                            ContactId = 74,
                            City = "West Melyssafort",
                            FlatNumber = "609D",
                            HouseNumber = "87663",
                            Mail = "Sarina.Schmeler@yahoo.com",
                            Phone = "183115557",
                            PostalCode = "14-097",
                            Street = "Mante Mall",
                            Voivodeship = "Nebraska"
                        },
                        new
                        {
                            ContactId = 75,
                            City = "New Janelleton",
                            FlatNumber = "877",
                            HouseNumber = "200",
                            Mail = "Myles48@yahoo.com",
                            Phone = "322789896",
                            PostalCode = "65-944",
                            Street = "Zane Knolls",
                            Voivodeship = "Minnesota"
                        },
                        new
                        {
                            ContactId = 76,
                            City = "Dibbertberg",
                            FlatNumber = "45",
                            HouseNumber = "567",
                            Mail = "Karina.Halvorson1@gmail.com",
                            Phone = "659531584",
                            PostalCode = "51-873",
                            Street = "Amos Dale",
                            Voivodeship = "Iowa"
                        },
                        new
                        {
                            ContactId = 77,
                            City = "Ronnyland",
                            FlatNumber = "9E",
                            HouseNumber = "75672",
                            Mail = "Hipolito.Osinski@yahoo.com",
                            Phone = "444736667",
                            PostalCode = "59-018",
                            Street = "Kevon Roads",
                            Voivodeship = "Wyoming"
                        },
                        new
                        {
                            ContactId = 78,
                            City = "Williamsonshire",
                            FlatNumber = "898",
                            HouseNumber = "3887",
                            Mail = "Keagan67@hotmail.com",
                            Phone = "254586466",
                            PostalCode = "53-162",
                            Street = "Ruben Street",
                            Voivodeship = "Missouri"
                        },
                        new
                        {
                            ContactId = 79,
                            City = "North Brent",
                            FlatNumber = "148",
                            HouseNumber = "20756",
                            Mail = "Alfreda_Armstrong@gmail.com",
                            Phone = "671303219",
                            PostalCode = "15-462",
                            Street = "Noemy Shoal",
                            Voivodeship = "Arkansas"
                        },
                        new
                        {
                            ContactId = 80,
                            City = "New Mabelleport",
                            FlatNumber = "299",
                            HouseNumber = "17892",
                            Mail = "Ressie29@yahoo.com",
                            Phone = "230165413",
                            PostalCode = "28-824",
                            Street = "Okuneva Orchard",
                            Voivodeship = "Idaho"
                        },
                        new
                        {
                            ContactId = 81,
                            City = "Haleyport",
                            FlatNumber = "633L",
                            HouseNumber = "272",
                            Mail = "Donnell.Terry@gmail.com",
                            Phone = "116375990",
                            PostalCode = "99-823",
                            Street = "Ahmad Ports",
                            Voivodeship = "California"
                        },
                        new
                        {
                            ContactId = 82,
                            City = "Gislasonmouth",
                            FlatNumber = "69",
                            HouseNumber = "29260",
                            Mail = "Emmie_Wisoky@gmail.com",
                            Phone = "998702168",
                            PostalCode = "46-775",
                            Street = "Bobby Underpass",
                            Voivodeship = "New Mexico"
                        },
                        new
                        {
                            ContactId = 83,
                            City = "North Jared",
                            FlatNumber = "69",
                            HouseNumber = "92017",
                            Mail = "Myah_Baumbach@yahoo.com",
                            Phone = "251244114",
                            PostalCode = "88-053",
                            Street = "Jeremy Loaf",
                            Voivodeship = "Vermont"
                        },
                        new
                        {
                            ContactId = 84,
                            City = "New Kian",
                            FlatNumber = "3",
                            HouseNumber = "15375",
                            Mail = "Wilford.Lebsack66@yahoo.com",
                            Phone = "722829118",
                            PostalCode = "53-621",
                            Street = "Katharina Pine",
                            Voivodeship = "Iowa"
                        },
                        new
                        {
                            ContactId = 85,
                            City = "East Dorthaside",
                            FlatNumber = "8",
                            HouseNumber = "648",
                            Mail = "Clair.Murray@hotmail.com",
                            Phone = "762179396",
                            PostalCode = "35-158",
                            Street = "Steuber Courts",
                            Voivodeship = "Montana"
                        },
                        new
                        {
                            ContactId = 86,
                            City = "South Carriebury",
                            FlatNumber = "514",
                            HouseNumber = "45240",
                            Mail = "Earnest_Cruickshank@yahoo.com",
                            Phone = "529163636",
                            PostalCode = "32-470",
                            Street = "Feil Light",
                            Voivodeship = "South Dakota"
                        },
                        new
                        {
                            ContactId = 87,
                            City = "North Laurenberg",
                            FlatNumber = "54R",
                            HouseNumber = "5485",
                            Mail = "Jaylin41@hotmail.com",
                            Phone = "764504521",
                            PostalCode = "08-093",
                            Street = "Jaden Lodge",
                            Voivodeship = "Hawaii"
                        },
                        new
                        {
                            ContactId = 88,
                            City = "New Shad",
                            FlatNumber = "28",
                            HouseNumber = "90628",
                            Mail = "Oral.Schuppe@gmail.com",
                            Phone = "181477652",
                            PostalCode = "42-152",
                            Street = "Abby Junction",
                            Voivodeship = "Connecticut"
                        },
                        new
                        {
                            ContactId = 89,
                            City = "Klockotown",
                            FlatNumber = "7",
                            HouseNumber = "1444",
                            Mail = "Maribel79@hotmail.com",
                            Phone = "321860512",
                            PostalCode = "79-282",
                            Street = "Gerhard Way",
                            Voivodeship = "Delaware"
                        },
                        new
                        {
                            ContactId = 90,
                            City = "Port Aldaton",
                            FlatNumber = "527P",
                            HouseNumber = "388",
                            Mail = "Greta.Lesch11@gmail.com",
                            Phone = "576569214",
                            PostalCode = "34-416",
                            Street = "Spencer Stravenue",
                            Voivodeship = "Washington"
                        },
                        new
                        {
                            ContactId = 91,
                            City = "Icieport",
                            FlatNumber = "3",
                            HouseNumber = "92451",
                            Mail = "Agustin.Kohler@yahoo.com",
                            Phone = "630869486",
                            PostalCode = "79-671",
                            Street = "Kailyn Keys",
                            Voivodeship = "Arizona"
                        },
                        new
                        {
                            ContactId = 92,
                            City = "Goyetteville",
                            FlatNumber = "79G",
                            HouseNumber = "08234",
                            Mail = "Marta_Collins@hotmail.com",
                            Phone = "747786529",
                            PostalCode = "26-930",
                            Street = "Pfannerstill Haven",
                            Voivodeship = "Minnesota"
                        },
                        new
                        {
                            ContactId = 93,
                            City = "Towneborough",
                            FlatNumber = "3",
                            HouseNumber = "00888",
                            Mail = "Mavis.Hilpert39@yahoo.com",
                            Phone = "215628241",
                            PostalCode = "07-724",
                            Street = "Garett Pike",
                            Voivodeship = "Vermont"
                        },
                        new
                        {
                            ContactId = 94,
                            City = "Ricoton",
                            FlatNumber = "6",
                            HouseNumber = "3746",
                            Mail = "Marco_Jaskolski@hotmail.com",
                            Phone = "365598563",
                            PostalCode = "78-722",
                            Street = "Viola Road",
                            Voivodeship = "Wisconsin"
                        },
                        new
                        {
                            ContactId = 95,
                            City = "West Sibyl",
                            FlatNumber = "99N",
                            HouseNumber = "78265",
                            Mail = "Graham_Lang27@hotmail.com",
                            Phone = "437263101",
                            PostalCode = "34-856",
                            Street = "Paris Mission",
                            Voivodeship = "Connecticut"
                        },
                        new
                        {
                            ContactId = 96,
                            City = "Bayerchester",
                            FlatNumber = "870",
                            HouseNumber = "88966",
                            Mail = "Lorenza37@yahoo.com",
                            Phone = "223330540",
                            PostalCode = "84-768",
                            Street = "Broderick Shore",
                            Voivodeship = "Florida"
                        },
                        new
                        {
                            ContactId = 97,
                            City = "Framibury",
                            FlatNumber = "467",
                            HouseNumber = "8037",
                            Mail = "Liana.Walter@hotmail.com",
                            Phone = "308105086",
                            PostalCode = "17-910",
                            Street = "Lakin Port",
                            Voivodeship = "Louisiana"
                        },
                        new
                        {
                            ContactId = 98,
                            City = "Wisokychester",
                            FlatNumber = "57",
                            HouseNumber = "12370",
                            Mail = "Dalton7@gmail.com",
                            Phone = "211884941",
                            PostalCode = "78-490",
                            Street = "Parker Lakes",
                            Voivodeship = "North Dakota"
                        },
                        new
                        {
                            ContactId = 99,
                            City = "Stoltenbergshire",
                            FlatNumber = "4",
                            HouseNumber = "9211",
                            Mail = "Michale.Flatley93@hotmail.com",
                            Phone = "165475553",
                            PostalCode = "85-962",
                            Street = "Nolan Cliffs",
                            Voivodeship = "Virginia"
                        },
                        new
                        {
                            ContactId = 100,
                            City = "Stehrberg",
                            FlatNumber = "2",
                            HouseNumber = "261",
                            Mail = "Jerod.Carter@hotmail.com",
                            Phone = "172264637",
                            PostalCode = "15-989",
                            Street = "Kailee Circles",
                            Voivodeship = "North Carolina"
                        });
                });

            modelBuilder.Entity("SwiezeBackend.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.Property<int>("UnitTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("ProductId");

                    b.HasIndex("UnitTypeId")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SwiezeBackend.Models.UnitType", b =>
                {
                    b.Property<int>("UnitTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("UnitTypeId");

                    b.ToTable("UnitTypes");

                    b.HasData(
                        new
                        {
                            UnitTypeId = 1,
                            Name = "payment"
                        },
                        new
                        {
                            UnitTypeId = 2,
                            Name = "Phased"
                        },
                        new
                        {
                            UnitTypeId = 3,
                            Name = "Baby"
                        },
                        new
                        {
                            UnitTypeId = 4,
                            Name = "Handcrafted"
                        },
                        new
                        {
                            UnitTypeId = 5,
                            Name = "microchip"
                        },
                        new
                        {
                            UnitTypeId = 6,
                            Name = "Product"
                        },
                        new
                        {
                            UnitTypeId = 7,
                            Name = "Engineer"
                        },
                        new
                        {
                            UnitTypeId = 8,
                            Name = "Trail"
                        },
                        new
                        {
                            UnitTypeId = 9,
                            Name = "Metrics"
                        },
                        new
                        {
                            UnitTypeId = 10,
                            Name = "calculating"
                        });
                });

            modelBuilder.Entity("SwiezeBackend.Models.Vendor", b =>
                {
                    b.Property<int>("VendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ContactId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("VendorId");

                    b.HasIndex("ContactId")
                        .IsUnique();

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("SwiezeBackend.Models.Client", b =>
                {
                    b.HasOne("SwiezeBackend.Models.Contact", "Contact")
                        .WithOne("Client")
                        .HasForeignKey("SwiezeBackend.Models.Client", "ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("SwiezeBackend.Models.Product", b =>
                {
                    b.HasOne("SwiezeBackend.Models.UnitType", "UnitType")
                        .WithOne("Product")
                        .HasForeignKey("SwiezeBackend.Models.Product", "UnitTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnitType");
                });

            modelBuilder.Entity("SwiezeBackend.Models.Vendor", b =>
                {
                    b.HasOne("SwiezeBackend.Models.Contact", "Contact")
                        .WithOne("Vendor")
                        .HasForeignKey("SwiezeBackend.Models.Vendor", "ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("SwiezeBackend.Models.Contact", b =>
                {
                    b.Navigation("Client");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("SwiezeBackend.Models.UnitType", b =>
                {
                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
